name: async_button_builder
description: A builder to wrap around buttons that handles loading, disabled,
  error and success states
version: 3.0.0+1
homepage: https://github.com/Nolence/async_button/tree/main/packages/async_button_builder

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  lint: ^2.3.0

flutter: null
