name: async_button_builder
description: A builder to wrap around buttons that handles loading, disabled,
  error and success states
version: 3.0.0+1
homepage: https://github.com/Nolence/async_button/tree/main/packages/async_button_builder

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
